const{test,expect} = require('@playwright/test')

test("Test Get API", async function({request}){
    const response = await request.get("https://jsonplaceholder.typicode.com/posts/1")
    const respbody= await response.body()
    const respjson = await response.json()
    const respstatus = await response.status()
    const respstatustext = await response.statusText()
    const respheaders = response.headers()
    const respheadersarray = response.headersArray()
    // console.log(respheadersarray)
    // console.log(respbody)
    // console.log(respheaders)
    // console.log(respjson)
    // console.log(respstatus)
    // console.log(respstatustext)

    expect(respstatus).toBe(200)
    expect(respstatustext).toBe('OK')  
    expect(response.ok()).toBeTruthy()
    expect(respjson).toHaveProperty("userId",1)
    expect(respjson).toHaveProperty("id",1)
    expect(respjson).toHaveProperty("title","sunt aut facere repellat provident occaecati excepturi optio reprehenderit")
    expect(respjson.body).toContain("quia et suscipit")
})